#!/usr/bin/env bash

mkdir -p compressed/

IFS=$'\n'
for space_filename in `ls *\ * 2> /dev/null`; do
    new_filename=`echo $space_filename | sed -e 's/ \+/_/g'`
    mv $space_filename $new_filename;
done

ppt_to_convert=`comm -23 <(ls *.pptx) <(ls *.pdf | sed -e 's:\.pdf:.pptx:')`
if [ -n "$ppt_to_convert" ]; then
    echo Converting $ppt_to_convert
    libreoffice --headless --convert-to pdf $ppt_to_convert
fi

pdf_to_compress=`comm -23 <(ls *.pdf) <(ls compressed/*.pdf | xargs -n 1 basename)`
if [ -n "$pdf_to_compress" ]; then
    echo Compressing $pdf_to_compress
    parallel -j 16 gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile=compressed/{} {} ::: $pdf_to_compress
fi
