#!/bin/bash
# https://stackoverflow.com/questions/15172735

win_list=`wmctrl -x -l | tr -s ' ' | cut -f 1,3 -d ' ' | grep -i $1 | cut -f1 -d ' '`
if [ -z $win_list ]; then
    echo "Cannot found window $1."
    exit 1
fi

active_win_id=`xprop -root | grep '^_NET_ACTIVE_W' | sed -r 's/.+# 0x([^,]+).*/0x0\1/g'`
if [ $((active_win_id)) -eq 0 ]; then
    active_win_id=""
fi

switch_to=`echo $win_list | sed -r "s/.*$active_win_id\s*(\S+).*/\1/"`
if [ -z $switch_to ]; then
   switch_to=`echo $win_list | cut -f1 -d' '`
fi

wmctrl -i -a $switch_to
