#!/usr/bin/env bash

usage() {
    echo Usage: $(basename $0) [FILE]
    exit 1
}

file="$@"
repo=/home/redbug312/.local/src/reveal.js

if [ -n "$file" ]; then
    readlink -f "$file" | xargs -I@ ln -sf @ $repo/slides.md
fi

cd $repo && npm start
