#!/usr/bin/env bash

if [ $# -gt 1 ]; then
    echo 'usage: bash reveal.bash <presentation.md>'
fi

REVEAL=/home/redbug312/.local/src/reveal.js

if [ -n "$1" ]; then
    readlink -f "$1" | xargs -I@ ln -sf @ $REVEAL/presentation.md
fi

cd $REVEAL && npm start
