#!/usr/bin/env bash

usage() {
    echo Usage: $(basename $0) [FILE]
    exit 1
}
[ $# -gt 1 ] && usage

file=$1
repo=/home/redbug312/.local/src/reveal.js

if [ -n "$file" ]; then
    readlink -f "$file" | xargs -I@ ln -sf @ $repo/presentation.md
fi

cd $repo && npm start
